### ISSUE TITLE
The first UTM parameter in the URL is not tracked

### ISSUE THREAD

**Issue by stannida** [matomo-org/plugin-MarketingCampaignsReporting#131] opened 2023-07-05 13:18 UTC
Hello,

I have a Marketing Campaigns Reporting activated on a Matomo On-Premise instance. In the config.ini.php there are the following configurations (same as in the documentation example):

> [MarketingCampaignsReporting]
> campaign_name = "matomo_campaign,mtm_cpn,utm_campaign"
> campaign_keyword = "mtm_keyword,matomo_kwd,mtm_kwd,utm_term"
> campaign_source = "mtm_source,utm_source"
> campaign_medium = "mtm_medium,utm_medium"
> campaign_content = "mtm_content,utm_content"
> campaign_id = "mtm_cid,utm_id,mtm_clid"
> campaign_group = "mtm_group"
> campaign_placement = "mtm_placement"

However, we have noticed that for some sessions the campaign source is missing (aka utm_source is not tracked). When testing the following UTM parameters attached to a URL this is what we see in the visits log and the same we get with the Reportings API:

?utm_source=test_source&utm_medium=test_medium&utm_campaign=test_campaign
<img width="382" alt="image" src="https://github.com/matomo-org/plugin-MarketingCampaignsReporting/assets/17237517/22708761-18a1-4064-8ea6-b432febabe28">

?utm_medium=test_medium&utm_source=test_source&utm_campaign=test_campaign
<img width="395" alt="image" src="https://github.com/matomo-org/plugin-MarketingCampaignsReporting/assets/17237517/079e9cb0-7bf1-4577-8d8e-2b450ee872cd">

?utm_medium=test_medium&utm_source=test_source
<img width="382" alt="image" src="https://github.com/matomo-org/plugin-MarketingCampaignsReporting/assets/17237517/866a03d1-8fd6-412c-afed-9be4f5cff77f">

It looks like the first parameter is consistently lost. There is nothing in the docu or issues about this problem, is there a bug or we have not installed something properly?

**Comment by snake14** [comment] 2023-07-05 20:52
Hi @stannida . I'm sorry to hear that you are experiencing this issue. Could you please provide a bit more information about your on-premise setup?

## Your Environment


* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by snake14** [comment] 2023-07-06 22:13
Hi @stannida . I tried to reproduce the issue you described, but when I tested passing several campaign parameters, all of them were recorded as expected.

In addition to the information I requested in my previous comment, could you please provide the version number of the MarketingCampaignsReporting plugin that you have installed?

**Comment by snake14** [comment] 2023-07-10 23:43
Hi @stannida I tried again to reproduce the issue and was unsuccessful. I copied the exact config values you specified, tried changing the order of the query parameters in the URL, and tried multiple browsers. As I'm unable to reproduce the issue and haven't received any further information from you, I'm going to close this issue. Please let me know if you need further assistance.

**Closed as completed by snake14** 2023-07-10 23:43 UTC
