### ISSUE TITLE
Plugin not setting default UTM config parameters on new install on 4.x

### ISSUE THREAD

**Issue by Starker3** [matomo-org/plugin-MarketingCampaignsReporting#64] opened 2021-03-03 01:58 UTC
Plugin version: 4.0.4
Matomo versions: 4.2.1 & 4.1.1
[matomo_system_check(1).txt](https://github.com/matomo-org/plugin-MarketingCampaignsReporting/files/6073061/matomo_system_check.1.txt)

When installing the plugin in 4.x it seems that the default campaign parameters are not set correctly.

Tracking request sent directly after plugin installed: 
![image](https://user-images.githubusercontent.com/20905821/109739723-ee1ab680-7c2e-11eb-8af7-6a05fb824ed2.png)

I then added the following to the config.ini.php (Copy/Paste from the plugin web page)
`[MarketingCampaignsReporting]
campaign_name = "matomo_campaign,mtm_cpn,utm_campaign"
campaign_keyword = "mtm_keyword,matomo_kwd,mtm_kwd,utm_term"
campaign_source = "mtm_source,utm_source"
campaign_medium = "mtm_medium,utm_medium"
campaign_content = "mtm_content,utm_content"
campaign_id = "mtm_cid,utm_id"
campaign_group = "mtm_group"
campaign_placement = "mtm_placement"`

Tracking request after manually adding config parameters the UTM parameters are tracked correctly:
![image](https://user-images.githubusercontent.com/20905821/109740060-7d27ce80-7c2f-11eb-95fa-94c62d987591.png)

**Comment by sgiehl** [comment] 2021-03-03 08:24
Guess that one might have occurred when updating php-di. Will have a quick look if it's easy to fix

**Comment by sgiehl** [comment] 2021-03-03 09:06
@Starker3  I've tried to reproduce that. Don't have a config set for the plugin, but the campaign parameters are detected correctly without any code change 🤔 
Do you have any custom values set for `[Tracker] campaign_var_name` or other campaign related configs?

**Comment by Starker3** [comment] 2021-03-04 19:45
@sgiehl I don't have any values in the config for `[Tracker] campaign_var_name` or any other campaign related configs.
What's interesting is it still works now after I remove the `[MarketingCampaignsReporting]` config that I manually set in the config.

I'll try to reproduce on a fresh install again and let you know if it occurs again or not.

**Comment by tsteur** [comment] 2021-08-03 21:27
@Starker3 did you end up still being able to reproduce this?

**Comment by Starker3** [comment] 2021-08-03 21:37
@tsteur I haven't tried again to reproduce this on a fresh install yet.

**Comment by tsteur** [comment] 2021-08-03 22:47
👍  I'll close this for now as we couldn't reproduce it. If someone is able to reproduce please comment here with the steps to reproduce and we'll reopen the issue

**Closed as completed by tsteur** 2021-08-03 22:47 UTC
Labels: worksforme
